version: '3.3'

services:
  php:
     image: wordpress:5-fpm
     volumes:
      - ./php-uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./:/var/www/html
     environment:
      WORDPRESS_DB_HOST: sdp-db.cuncngfmxyly.ap-southeast-1.rds.amazonaws.com
      WORDPRESS_DB_USER: sdproot
      WORDPRESS_DB_PASSWORD: upsdp1933
      WORDPRESS_DB_NAME: sdp_db
      WORDPRESS_TABLE_PREFIX: sdp

  web:
     image: nginx
     depends_on:
      - php
     restart: always
     volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
      - ./logs:/var/log/nginx

  https-portal:
    image: steveltn/https-portal:1
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./ssl_certs:/var/lib/https-portal
    environment:
      DOMAINS: 'localhost -> http://web:80 #local'
      CLIENT_MAX_BODY_SIZE: 64M