version: '3.3'

services:
  https-portal:
    image: steveltn/https-portal
    ports:
      - 80:80
      - 443:443
    links:
      - wordpress
    environment:
      - "DOMAINS=3.0.94.98 -> http://wordpress"
#      - "PRODUCTION=true"

  wordpress:
      image: wordpress:latest
      volumes:
        - ./:/var/www/html
      restart: always
      environment:
        WORDPRESS_DB_HOST: sdp-db.cuncngfmxyly.ap-southeast-1.rds.amazonaws.com
        WORDPRESS_DB_USER: sdproot
        WORDPRESS_DB_PASSWORD: upsdp1933
        WORDPRESS_DB_NAME: sdp_db
        WORDPRESS_TABLE_PREFIX: sdp