version: "3.3"

services:
  wordpress:
    container_name: sdp_wp
    image: wordpress:latest
    restart: unless-stopped
    volumes:
      - ${WP_CORE}:/var/www/html
      - ${WP_CONTENT}:/var/www/html/wp-content
    ports:
      - '80:80'
      - '443:443'
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
#       VIRTUAL_HOST: ${DOMAINS}
#       LETSENCRYPT_HOST: ${DOMAINS}
#       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

# networks:
#   default:
#     external:
#       name: ${NETWORK:-webproxy}
