version: '3.3'

services:
  wordpress:
    image: wordpress:latest
    volumes:
      - ./:/var/www/html
    ports:
      - '80:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: sdp-db.cuncngfmxyly.ap-southeast-1.rds.amazonaws.com
      WORDPRESS_DB_USER: sdproot
      WORDPRESS_DB_PASSWORD: upsdp1933
